version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.10.0'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  lint:
    executor:
      name: node/default
      tag: '16.10.0'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run lint

  test:
    executor:
      name: node/default
      tag: '16.10.0'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test:coverage
      - run: npm run codecov

  publish:
    executor:
      name: node/default
      tag: '16.10.0'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish ~/project --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
