# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.3

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  build-lib:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run build && npm run copy-files
      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib

  lint-lib:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run lint


  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: cp ~/repo/README.md ~/repo/lib/README.md
      - run: cp ~/repo/package.json ~/repo/lib/package.json
      - run: cp ~/repo/postinstall.sh ~/repo/lib/postinstall.sh
      - run: npm publish ~/repo/lib --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build-lib:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - lint-lib:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build-lib
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
